language: objective-c
script: 
  - xcodebuild -project TJTestTravisCi/TJTestTravisCi.xcodeproj -scheme TJTestTravisCiTests build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)